### ISSUE TITLE
Mock paper 1 question 21

### ISSUE THREAD

**Issue by pohjie** [nus-cs2103-AY1718S1/forum#237] opened 2017-11-28 12:15 UTC
Hello,

According to the textbook, composition implies that there cannot be cyclical links. In this question, a cyclical link occurs. Do we still put true as the answer?

**Comment by damithc** [comment] 2017-11-28 13:42
Duplicate of #234

**Closed as completed by damithc** 2017-11-28 13:42 UTC
Labels: type-Question, week.14

**Comment by damithc** [comment] 2017-11-28 13:44
@pohjie reopen if #234 doesn't clarify your doubt
